### ISSUE TITLE
Question on evaluation protocol used in paper

### ISSUE THREAD

**Issue by levan92** [liruilong940607/OCHumanApi#12]
I would like to check some details in your paper "Pose2Seg: Detection Free Human Instance Segmentation". For the AP scores reported in Tables 2 & 3, can I check if these scores are evaluated on what type of IOU computation (bounding box or segmentation)? To be specific, I am refering to the `iouType` here https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/cocoeval.py

**Comment by liruilong940607** [comment]
Hi. Those are segmentation iou. a.k.a `segm` for `iouType`

**Comment by levan92** [comment]
Alright, thank you!
