### ISSUE TITLE
Why only some people are marked?

### ISSUE THREAD

**Issue by jianlong-yuan** [liruilong940607/OCHumanApi#2]
Why only some people are marked, others in a picture are not marked?

![image](https://user-images.githubusercontent.com/18137551/55377682-a2de6180-5548-11e9-8cf9-9a59b05990fe.png)

**Comment by liruilong940607** [comment]
We annotated all the bounding-boxes. But because mask & key-point annotation is a quite time-consuming job, a few instances have no such annotation. (It doesn't affect the evaluation.) Our visualisation code shows instances with full annotations here.

**Comment by chamecall** [comment]
> We annotated all the bounding-boxes. But because mask & key-point annotation is a quite time-consuming job, a few instances have no such annotation. (It doesn't affect the evaluation.) Our visualisation code shows instances with full annotations here.

hello, I'm wondering how you've obtained evaluation with the face that some instances not annoted?
like for example you've got predictions of two instances for the image above but we have only one gt instance.

what's the logic to match specific prediction instance with its according gt instance? Something like bounding box closeness or what?

**Comment by liruilong940607** [comment]
The coco evaluation toolbox can tolerate case like this.

I can't remember precisely but the logic is something like for each gt, you find a prediction that has max iou with it, and consider it as a match.
